### ISSUE TITLE
文章侧边栏中站点概述能将Blog Cover更换成 Author Avatar 吗

### ISSUE THREAD

**Issue by HugeTimor** [microud/ghost-theme-next#1]
您好，我的博客是使用了你的模板，非常不错，简洁美观。如何将文章侧边栏中站点概述能将Blog Cover更换成 Author Avatar 。

![image](https://cloud.githubusercontent.com/assets/8110701/15503918/f9ebb74c-21ee-11e6-98cb-1b00808264f2.png)

**Comment by nagaame** [comment]
在partials文件夹下的sidebar.hbs修改第三行代码中的`src="{{@blog.cover}}"`成`src="{{@blog.logo}}"`就可以了

**Comment by HugeTimor** [comment]
ok了，谢谢。
